name = "Spectestpack"
author = "KatTheFox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca5998cf431c9c9aa119b4b480ca97a74b6834a39265b9db1a7a9b28ac8fd679"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
